# Dockerfile для контейнера Nginx
FROM nginx:latest

# Копирование конфигурационного файла Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

# Открытие порта 80 для входящих подключений
EXPOSE 80
